# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window.ui'
#
# Created by: PyQt5 UI code generator 5.12
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1068, 937)
        self.gridLayout_2 = QtWidgets.QGridLayout(Form)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.selectimg_combobox = QtWidgets.QComboBox(Form)
        self.selectimg_combobox.setObjectName("selectimg_combobox")
        self.gridLayout.addWidget(self.selectimg_combobox, 8, 1, 1, 2)
        self.price_label = QtWidgets.QLabel(Form)
        self.price_label.setObjectName("price_label")
        self.gridLayout.addWidget(self.price_label, 5, 0, 1, 1)
        self.fetchlistings_btn = QtWidgets.QPushButton(Form)
        self.fetchlistings_btn.setObjectName("fetchlistings_btn")
        self.gridLayout.addWidget(self.fetchlistings_btn, 1, 2, 1, 1)
        self.catname_label = QtWidgets.QLabel(Form)
        self.catname_label.setObjectName("catname_label")
        self.gridLayout.addWidget(self.catname_label, 3, 0, 1, 1)
        self.meanprice_val = QtWidgets.QLabel(Form)
        self.meanprice_val.setMinimumSize(QtCore.QSize(70, 0))
        self.meanprice_val.setObjectName("meanprice_val")
        self.gridLayout.addWidget(self.meanprice_val, 4, 4, 1, 1)
        self.medianprice_label = QtWidgets.QLabel(Form)
        self.medianprice_label.setObjectName("medianprice_label")
        self.gridLayout.addWidget(self.medianprice_label, 5, 3, 1, 1, QtCore.Qt.AlignRight)
        self.catid_field = QtWidgets.QLineEdit(Form)
        self.catid_field.setObjectName("catid_field")
        self.gridLayout.addWidget(self.catid_field, 4, 1, 1, 2)
        self.price_field = QtWidgets.QLineEdit(Form)
        self.price_field.setObjectName("price_field")
        self.gridLayout.addWidget(self.price_field, 5, 1, 1, 2)
        self.shipping_field = QtWidgets.QLineEdit(Form)
        self.shipping_field.setObjectName("shipping_field")
        self.gridLayout.addWidget(self.shipping_field, 6, 1, 1, 2)
        self.listingstats_label = QtWidgets.QLabel(Form)
        self.listingstats_label.setObjectName("listingstats_label")
        self.gridLayout.addWidget(self.listingstats_label, 1, 3, 1, 2, QtCore.Qt.AlignHCenter)
        self.minprice_label = QtWidgets.QLabel(Form)
        self.minprice_label.setObjectName("minprice_label")
        self.gridLayout.addWidget(self.minprice_label, 2, 3, 1, 1, QtCore.Qt.AlignRight)
        self.numlistings_val = QtWidgets.QLabel(Form)
        self.numlistings_val.setObjectName("numlistings_val")
        self.gridLayout.addWidget(self.numlistings_val, 6, 4, 1, 1)
        self.maxprice_label = QtWidgets.QLabel(Form)
        self.maxprice_label.setObjectName("maxprice_label")
        self.gridLayout.addWidget(self.maxprice_label, 3, 3, 1, 1, QtCore.Qt.AlignRight)
        self.numlistings_label = QtWidgets.QLabel(Form)
        self.numlistings_label.setObjectName("numlistings_label")
        self.gridLayout.addWidget(self.numlistings_label, 6, 3, 1, 1)
        self.appheader_label = QtWidgets.QLabel(Form)
        self.appheader_label.setObjectName("appheader_label")
        self.gridLayout.addWidget(self.appheader_label, 0, 0, 1, 1)
        self.catname_field = QtWidgets.QLineEdit(Form)
        self.catname_field.setObjectName("catname_field")
        self.gridLayout.addWidget(self.catname_field, 3, 1, 1, 2)
        self.upc_label = QtWidgets.QLabel(Form)
        self.upc_label.setObjectName("upc_label")
        self.gridLayout.addWidget(self.upc_label, 1, 0, 1, 1)
        self.title_field = QtWidgets.QLineEdit(Form)
        self.title_field.setObjectName("title_field")
        self.gridLayout.addWidget(self.title_field, 2, 1, 1, 2)
        self.title_label = QtWidgets.QLabel(Form)
        self.title_label.setObjectName("title_label")
        self.gridLayout.addWidget(self.title_label, 2, 0, 1, 1)
        self.catid_label = QtWidgets.QLabel(Form)
        self.catid_label.setObjectName("catid_label")
        self.gridLayout.addWidget(self.catid_label, 4, 0, 1, 1)
        self.upc_field = QtWidgets.QLineEdit(Form)
        self.upc_field.setObjectName("upc_field")
        self.gridLayout.addWidget(self.upc_field, 1, 1, 1, 1)
        self.medianprice_val = QtWidgets.QLabel(Form)
        self.medianprice_val.setMinimumSize(QtCore.QSize(70, 0))
        self.medianprice_val.setObjectName("medianprice_val")
        self.gridLayout.addWidget(self.medianprice_val, 5, 4, 1, 1)
        self.search_btn = QtWidgets.QPushButton(Form)
        self.search_btn.setObjectName("search_btn")
        self.gridLayout.addWidget(self.search_btn, 0, 4, 1, 1)
        self.maxprice_val = QtWidgets.QLabel(Form)
        self.maxprice_val.setMinimumSize(QtCore.QSize(70, 0))
        self.maxprice_val.setObjectName("maxprice_val")
        self.gridLayout.addWidget(self.maxprice_val, 3, 4, 1, 1)
        self.search_field = QtWidgets.QLineEdit(Form)
        self.search_field.setObjectName("search_field")
        self.gridLayout.addWidget(self.search_field, 0, 2, 1, 2)
        self.meanprice_label = QtWidgets.QLabel(Form)
        self.meanprice_label.setObjectName("meanprice_label")
        self.gridLayout.addWidget(self.meanprice_label, 4, 3, 1, 1, QtCore.Qt.AlignRight)
        self.minprice_val = QtWidgets.QLabel(Form)
        self.minprice_val.setMinimumSize(QtCore.QSize(70, 0))
        self.minprice_val.setObjectName("minprice_val")
        self.gridLayout.addWidget(self.minprice_val, 2, 4, 1, 1)
        self.pricedistribution_label = QtWidgets.QLabel(Form)
        self.pricedistribution_label.setMinimumSize(QtCore.QSize(0, 30))
        self.pricedistribution_label.setTextFormat(QtCore.Qt.AutoText)
        self.pricedistribution_label.setObjectName("pricedistribution_label")
        self.gridLayout.addWidget(self.pricedistribution_label, 8, 3, 1, 2, QtCore.Qt.AlignHCenter)
        self.shipping_label = QtWidgets.QLabel(Form)
        self.shipping_label.setObjectName("shipping_label")
        self.gridLayout.addWidget(self.shipping_label, 6, 0, 1, 1)
        self.price_dist_img = QtWidgets.QLabel(Form)
        self.price_dist_img.setMinimumSize(QtCore.QSize(566, 436))
        self.price_dist_img.setText("")
        self.price_dist_img.setObjectName("price_dist_img")
        self.gridLayout.addWidget(self.price_dist_img, 10, 3, 1, 2, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.selectimg_label = QtWidgets.QLabel(Form)
        self.selectimg_label.setObjectName("selectimg_label")
        self.gridLayout.addWidget(self.selectimg_label, 8, 0, 1, 1)
        self.description_label = QtWidgets.QLabel(Form)
        self.description_label.setObjectName("description_label")
        self.gridLayout.addWidget(self.description_label, 7, 0, 1, 1)
        self.description_field = QtWidgets.QPlainTextEdit(Form)
        self.description_field.setMinimumSize(QtCore.QSize(0, 0))
        self.description_field.setObjectName("description_field")
        self.gridLayout.addWidget(self.description_field, 7, 1, 1, 2)
        self.imgurl_label = QtWidgets.QLabel(Form)
        self.imgurl_label.setObjectName("imgurl_label")
        self.gridLayout.addWidget(self.imgurl_label, 9, 0, 1, 1)
        self.imgurl_field = QtWidgets.QLineEdit(Form)
        self.imgurl_field.setObjectName("imgurl_field")
        self.gridLayout.addWidget(self.imgurl_field, 9, 1, 1, 2)
        self.clear_btn = QtWidgets.QPushButton(Form)
        self.clear_btn.setObjectName("clear_btn")
        self.gridLayout.addWidget(self.clear_btn, 11, 4, 1, 1)
        self.save_btn = QtWidgets.QPushButton(Form)
        self.save_btn.setObjectName("save_btn")
        self.gridLayout.addWidget(self.save_btn, 11, 3, 1, 1)
        self.product_img = QtWidgets.QLabel(Form)
        self.product_img.setText("")
        self.product_img.setObjectName("product_img")
        self.gridLayout.addWidget(self.product_img, 10, 0, 1, 3)
        self.gridLayout_2.addLayout(self.gridLayout, 1, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.price_label.setText(_translate("Form", "Price:"))
        self.fetchlistings_btn.setText(_translate("Form", "Fetch Listings"))
        self.catname_label.setText(_translate("Form", "Category name:"))
        self.meanprice_val.setText(_translate("Form", "N/A"))
        self.medianprice_label.setText(_translate("Form", "<html><head/><body><p><span style=\" font-style:italic;\">Median Price:</span></p></body></html>"))
        self.listingstats_label.setText(_translate("Form", "<html><head/><body><p><span style=\" font-weight:600;\">Completed Listing Statistics</span></p></body></html>"))
        self.minprice_label.setText(_translate("Form", "<html><head/><body><p><span style=\" font-style:italic;\">Min Price:</span></p></body></html>"))
        self.numlistings_val.setText(_translate("Form", "N/A"))
        self.maxprice_label.setText(_translate("Form", "<html><head/><body><p><span style=\" font-style:italic;\">Max Price:</span></p></body></html>"))
        self.numlistings_label.setText(_translate("Form", "<html><head/><body><p align=\"right\"><span style=\" font-style:italic;\"># Listings:</span></p></body></html>"))
        self.appheader_label.setText(_translate("Form", "<html><head/><body><p><span style=\" font-weight:600; text-decoration: underline;\">Product Details</span></p></body></html>"))
        self.upc_label.setText(_translate("Form", "UPC code:"))
        self.title_label.setText(_translate("Form", "Product title:"))
        self.catid_label.setText(_translate("Form", "Category ID:"))
        self.medianprice_val.setText(_translate("Form", "N/A"))
        self.search_btn.setText(_translate("Form", "Search"))
        self.maxprice_val.setText(_translate("Form", "N/A"))
        self.meanprice_label.setText(_translate("Form", "<html><head/><body><p><span style=\" font-style:italic;\">Mean Price:</span></p></body></html>"))
        self.minprice_val.setText(_translate("Form", "N/A"))
        self.pricedistribution_label.setText(_translate("Form", "<html><head/><body><p><span style=\" font-weight:600;\">Price Distribution</span></p></body></html>"))
        self.shipping_label.setText(_translate("Form", "Shipping:"))
        self.selectimg_label.setText(_translate("Form", "Select image:"))
        self.description_label.setText(_translate("Form", "Description:"))
        self.imgurl_label.setText(_translate("Form", "Image URL:"))
        self.clear_btn.setText(_translate("Form", "Clear"))
        self.save_btn.setText(_translate("Form", "Save"))


